version: '3'

services:
  php:
    build:
      context: config/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PHP_VERSION: ${PHP_VERSION}
        PHP_TIMEZONE: ${PHP_TIMEZONE}
        NODE_JS_VERSION: ${NODE_JS_VERSION}
    volumes:
      - ${PROJECT_PATH}:/var/www/project:cached
      - ${SYMFONY_LOG_PATH}:/var/www/project/var/logs:cached
      - ${COMPOSER_PATH}/cache:/var/www/.composer/cache:cached
      - ${SSH_KEY_PATH}:/var/www/.ssh
      - ${USER_CONFIG_PATH}/.bash_history:/var/www/.bash_history
      - ./config/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

  nginx:
    build:
      context: config/nginx
      args:
        PROJECT_DOMAIN: ${PROJECT_DOMAIN}
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - ${PORT_NGINX}:80
    networks:
      default:
        aliases:
          - ${PROJECT_DOMAIN}
    volumes:
      - ${PROJECT_PATH}:/var/www/project:cached
      - ${NGINX_LOG_PATH}:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${PORT_MYSQL}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql:cached

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - ${PORT_PHPMYADMIN}:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"